"""The compose file's text, written from the editor block of `consuming.json`.

**What it does.** `service(editor)` returns the lines of the editor's service,
every value and every comment taken from the contract block it is given, and
`HEADER` is what every rendered file opens with. `scalar(key, value)` spells
one YAML scalar.

**Why it is a module of its own.** `consuming.py` reached the 400-line bound
for a source file, and this is its seam: that module decides WHETHER a contract may be
rendered (`findings`, `render`'s refusal), this one only writes the text of a
contract already accepted. ⛔ Nothing here checks a ruling, so it is only ever
called through `consuming.render`.

**Depends on.** The standard library only.
"""

from __future__ import annotations

import textwrap

#: The header every rendered file carries: it is a template, never an include.
HEADER = (
    "# ⛔ A TEMPLATE TO COPY AND ADAPT — never an `include:` and never a file to",
    "# reference from another compose project. The mount list is exactly the part",
    "# that must differ per project, so a shared file would be wrong for everyone.",
    "#",
    "# ⭐ Generated by `consuming/consuming.py` from `consuming.json`, which is this",
    "# component's contract and the only input. Edit the contract, not this file;",
    "# then copy it into your own repository and adapt it there.",
    "#",
    "# ⛔ No Docker socket is mounted here or anywhere else: it would be root on the host.",
)



def service(editor: dict) -> list[str]:
    at = "    "
    lines = [
        *_comment("The image a consumer PINS. It has no registry: build it from this component's "
                  "checkout and pin the tag the build prints:", at),
        f"{at}#   {' '.join(editor['image']['tag_from'])}",
        *_comment(editor["image"]["tag"]["how_to_pin"], at),
        scalar("image", editor["image"]["compose_value"], at),
        *_comment(editor["runs_as"]["why"], at),
        scalar(editor["runs_as"]["compose_key"], editor["runs_as"]["compose_value"], at),
        *_comment(editor["why_restart_no"], at),
        scalar("restart", editor["restart"], at),
        *_comment(editor["filesystem"]["why"], at),
        scalar(editor["filesystem"]["compose_key"], editor["filesystem"]["compose_value"], at),
        f"{at}environment:",
    ]
    for entry in editor["environment"]:
        lines += _comment(entry.get("note", ""), f"{at}  ")
        lines.append(scalar(entry["name"], entry.get("compose_value") or entry["default"], f"{at}  "))
    lines.append(f"{at}ports:")
    for port in editor["ports"]:
        lines += _comment(port["why"], f"{at}  ")
        lines.append(f'{at}  - "{port["host_bind"]}:{port["host"]}:{port["container"]}"')
    lines += [*_comment(editor["workspace"]["why"], at), f"{at}tmpfs:",
              f"{at}  - {editor['workspace']['container_path']}", f"{at}volumes:"]
    for mount in editor["mounts"]:
        lines += _comment(mount["purpose"], f"{at}  ")
        if mount["kind"] == "bind":
            lines += _comment("⛔ This source must exist on the host BEFORE the container starts, or "
                              "docker creates it root-owned and nothing in the container can write it.",
                              f"{at}  ")
        source = mount["host_path"] if mount["kind"] == "bind" else mount["volume"]
        suffix = ":ro" if mount["read_only"] else ""
        lines.append(f'{at}  - "{source}:{mount["container_path"]}{suffix}"')
    lines += [*_comment(editor["command_notes"]["auth"], at),
              *_comment(editor["command_notes"]["bind_addr"], at),
              *_comment(editor["command_notes"]["workspace_trust"], at), f"{at}command:"]
    lines += [f'{at}  - "{_escaped(argument)}"' for argument in editor["command"]]
    lines += [*_comment(editor["healthcheck"]["ordering"], at), f"{at}healthcheck:"]
    lines += _healthcheck(editor["healthcheck"], f"{at}  ")
    return lines


def _comment(text: str, at: str = "") -> list[str]:
    """A prose value from the contract, wrapped so the rendered file stays readable."""
    if not text.strip():
        return []
    return [f"{at}# {line}" for line in textwrap.wrap(text, width=78 - len(at))]


def _healthcheck(health: dict, at: str) -> list[str]:
    test = ", ".join(f'"{_escaped(part)}"' for part in health["command"])
    lines = [f"{at}test: [{test}]"]
    for key, suffix in (("start_period", "s"), ("start_interval", "s"), ("interval", "s"), ("timeout", "s")):
        lines.append(f"{at}{key}: {health[f'{key}_seconds']}{suffix}")
    return lines + [f"{at}retries: {health['retries']}"]


def scalar(key: str, value, at: str = "") -> str:
    if isinstance(value, bool):  # YAML's spelling, not Python's
        return f"{at}{key}: {str(value).lower()}"
    if isinstance(value, int):
        return f"{at}{key}: {value}"
    return f'{at}{key}: "{_escaped(str(value))}"'


def _escaped(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')
