"""The consuming contract: read `consuming.json`, refuse what breaks it, render a compose file.

**What it does.** Reads this component's `consuming.json` — the machine-readable
half of `docs/consuming.md` — checks it against the rulings a consumer inherits,
and renders a complete, working compose file from it and nothing else.

**How you use it.** From the component root:

    python3 consuming/consuming.py --check           # the rulings, on the real contract
    python3 consuming/consuming.py --render          # the reference fragment, to stdout
    python3 consuming/consuming.py --write docs/compose.reference.yaml

`load(root)` reads the file; `findings(contract)` returns what is wrong with it,
empty when nothing is; `render(contract, ...)` returns the compose file's text
and **refuses** a contract with a finding rather than emitting one that breaks a
ruling.

**Depends on.** The standard library only. ⛔ It reads no Dockerfile, starts no
container and mounts no socket.

## ⛔ Why a renderer and not a checked-in example

The epic's acceptance is that `consuming.json` is *sufficient to generate a
working compose file with no other input*. A hand-written example cannot show
that: it would be a second copy of the contract, drifting quietly. So the
reference fragment beside `docs/consuming.md` is **generated by this module**
and a test asserts the checked-in file is what the contract renders today.

⭐ Per-project values — the project name, the host port, the uid:gid, the source
paths — arrive as compose **interpolations** with defaults (`${HOST_UID:-1000}`)
or as this module's keyword arguments. So the rendered file needs no argument to
be complete, and a consumer still adapts every part that must differ.

## ⛔ What the rendered file may never say

§8.3 is the non-negotiable: no Docker socket reaches a serving process. The four
rulings E12 gives a consumer are the rest — loopback-only publishing, the sources
and nothing else, the repository owner's uid:gid, and a bind source that exists
before the container starts. `findings` asserts each of them against the data, so
a contract edited into breaking one stops here instead of in somebody's browser.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path

COMPONENT = Path(__file__).resolve().parents[1]
CONSUMING = "consuming.json"
#: Where the rendered reference lives, relative to the component root.
REFERENCE = "docs/compose.reference.yaml"
#: The addresses that keep an unencrypted IDE on this machine.
LOOPBACK = ("127.0.0.1", "::1", "localhost")
#: The header every rendered file carries: it is a template, never an include.
HEADER = (
    "# ⛔ A TEMPLATE TO COPY AND ADAPT — never an `include:` and never a file to",
    "# reference from another compose project. The mount list is exactly the part",
    "# that must differ per project, so a shared file would be wrong for everyone.",
    "#",
    f"# ⭐ Generated by `consuming/consuming.py` from `{CONSUMING}`, which is this",
    "# component's contract and the only input. Edit the contract, not this file;",
    "# then copy it into your own repository and adapt it there.",
    "#",
    "# ⛔ No Docker socket is mounted here or anywhere else (spec §8.3).",
)


class Refused(ValueError):
    """A contract that will not be rendered, and which ruling it breaks."""


def load(root: Path = COMPONENT) -> dict:
    return json.loads((Path(root) / CONSUMING).read_text(encoding="utf-8"))


# --------------------------------------------------------------- the rulings
def findings(contract: dict) -> list[str]:
    """What is wrong with the contract, empty when nothing is."""
    editor = contract.get("editor", {})
    found: list[str] = []
    found += _socket_findings(editor)
    found += _port_findings(editor)
    found += _user_findings(editor)
    found += _mount_findings(editor)
    found += _ordering_findings(editor)
    found += _environment_findings(editor)
    return found


def _socket_findings(editor: dict) -> list[str]:
    """§8.3: never, not behind a flag and not only locally."""
    found = []
    if editor.get("docker_socket") is not False:
        found.append("docker_socket is not declared false: the Docker socket is never mounted (spec §8.3)")
    for mount in editor.get("mounts", []):
        if "docker.sock" in f"{mount.get('host_path', '')}{mount.get('container_path', '')}":
            found.append(f"a mount names the Docker socket: {mount.get('container_path')} (spec §8.3)")
    return found


def _port_findings(editor: dict) -> list[str]:
    """Loopback-only port binding, never 0.0.0.0."""
    found = []
    bound = {port.get("container") for port in editor.get("ports", [])}
    for port in editor.get("ports", []):
        where = port.get("host_bind")
        if where not in LOOPBACK or port.get("publish_on_all_interfaces") is not False:
            found.append(f"port {port.get('container')} is published on {where!r}: an unencrypted IDE "
                         "with a shell binds loopback only")
    for argument in editor.get("command", []):
        if not argument.startswith("--bind-addr"):
            continue
        inside = re.fullmatch(r"--bind-addr=(?P<host>[\w.:\[\]]+):(?P<port>\d+)", argument)
        if not inside or int(inside["port"]) not in bound:
            found.append(f"the command binds {argument!r}, which no ports entry publishes")
    return found


def _user_findings(editor: dict) -> list[str]:
    """Run as the repository owner's uid:gid, or the files it writes are root's."""
    runs_as = editor.get("runs_as", {})
    if runs_as.get("uid") in (None, 0) or runs_as.get("gid") in (None, 0):
        return ["runs_as is root or absent: the container runs as the uid:gid that owns the sources"]
    if not runs_as.get("compose_value"):
        return ["runs_as names no compose value, so a consumer has nothing to put under `user:`"]
    return []


def _mount_findings(editor: dict) -> list[str]:
    """Only the sources are mounted, and a bind source exists before the container starts."""
    workspace = editor.get("workspace", {})
    root = workspace.get("container_path")
    found = []
    if not root or workspace.get("kind") != "tmpfs":
        found.append("the workspace root is not a tmpfs: docker would create it root-owned and no "
                     "build could write into it")
    for mount in editor.get("mounts", []):
        path, kind = mount.get("container_path", ""), mount.get("kind")
        if kind != "bind":
            continue
        if not root or not path.startswith(f"{root}/"):
            found.append(f"the bind at {path} is outside the workspace {root!r}: only the sources are "
                         "mounted, not the repository and not $HOME")
        if mount.get("must_exist_before_start") is not True:
            found.append(f"the bind at {path} does not say its source must exist before the container "
                         "starts; docker creates a missing one root-owned")
    return found


def _ordering_findings(editor: dict) -> list[str]:
    """Ordering is enforced by a health check, not by hope."""
    health = editor.get("healthcheck", {})
    missing = [key for key in ("command", "path", "expect_status", "ordering") if not health.get(key)]
    return [f"the healthcheck declares no {key}: ordering is enforced by a health check, not by hope"
            for key in missing]


def _environment_findings(editor: dict) -> list[str]:
    """A variable with no default is required, and one with a default is not."""
    found = []
    for entry in editor.get("environment", []):
        name, default, required = entry.get("name"), entry.get("default"), entry.get("required")
        if required and default is not None:
            found.append(f"{name} is required and defaulted: a consumer cannot tell which the image expects")
        if required and not entry.get("compose_value"):
            found.append(f"{name} has no default and no compose value, so a consumer has nothing to write")
    return found


# ------------------------------------------------------------- the rendering
def render(contract: dict, *, project: str = "studyforge-editor", service: str = "editor") -> str:
    """The compose file this contract describes, or `Refused` naming the ruling it breaks."""
    broken = findings(contract)
    if broken:
        raise Refused("; ".join(broken))
    editor = contract["editor"]
    lines = [*HEADER, "", _scalar("name", project), "", "services:", f"  {service}:"]
    lines += _service(editor)
    volumes = [mount["volume"] for mount in editor["mounts"] if mount["kind"] == "volume"]
    if volumes:
        lines += ["", "volumes:"] + [f"  {name}:" for name in volumes]
    return "\n".join(lines) + "\n"


def _service(editor: dict) -> list[str]:
    at = "    "
    lines = [
        *_comment("The image a consumer PINS. It has no registry: build it from this component's "
                  "checkout and pin the tag the build prints:", at),
        f"{at}#   {' '.join(editor['image']['tag_from'])}",
        _scalar("image", editor["image"]["compose_value"], at),
        *_comment(editor["runs_as"]["why"], at),
        _scalar(editor["runs_as"]["compose_key"], editor["runs_as"]["compose_value"], at),
        *_comment(editor["why_restart_no"], at),
        _scalar("restart", editor["restart"], at),
        f"{at}environment:",
    ]
    for entry in editor["environment"]:
        lines += _comment(entry.get("note", ""), f"{at}  ")
        lines.append(_scalar(entry["name"], entry.get("compose_value") or entry["default"], f"{at}  "))
    lines.append(f"{at}ports:")
    for port in editor["ports"]:
        lines += _comment(port["why"], f"{at}  ")
        lines.append(f'{at}  - "{port["host_bind"]}:{port["host"]}:{port["container"]}"')
    lines += [*_comment(editor["workspace"]["why"], at), f"{at}tmpfs:",
              f"{at}  - {editor['workspace']['container_path']}", f"{at}volumes:"]
    for mount in editor["mounts"]:
        lines += _comment(mount["purpose"], f"{at}  ")
        if mount["kind"] == "bind":
            lines += _comment("⛔ This source must exist on the host BEFORE the container starts, or "
                              "docker creates it root-owned and nothing in the container can write it.",
                              f"{at}  ")
        source = mount["host_path"] if mount["kind"] == "bind" else mount["volume"]
        suffix = ":ro" if mount["read_only"] else ""
        lines.append(f'{at}  - "{source}:{mount["container_path"]}{suffix}"')
    lines += [*_comment(editor["command_notes"]["bind_addr"], at), f"{at}command:"]
    lines += [f'{at}  - "{_escaped(argument)}"' for argument in editor["command"]]
    lines += [*_comment(editor["healthcheck"]["ordering"], at), f"{at}healthcheck:"]
    lines += _healthcheck(editor["healthcheck"], f"{at}  ")
    return lines


def _comment(text: str, at: str = "") -> list[str]:
    """A prose value from the contract, wrapped so the rendered file stays readable."""
    if not text.strip():
        return []
    return [f"{at}# {line}" for line in textwrap.wrap(text, width=78 - len(at))]


def _healthcheck(health: dict, at: str) -> list[str]:
    test = ", ".join(f'"{_escaped(part)}"' for part in health["command"])
    lines = [f"{at}test: [{test}]"]
    for key, suffix in (("start_period", "s"), ("start_interval", "s"), ("interval", "s"), ("timeout", "s")):
        lines.append(f"{at}{key}: {health[f'{key}_seconds']}{suffix}")
    return lines + [f"{at}retries: {health['retries']}"]


def _scalar(key: str, value, at: str = "") -> str:
    if isinstance(value, bool) or isinstance(value, int):
        return f"{at}{key}: {value}"
    return f'{at}{key}: "{_escaped(str(value))}"'


def _escaped(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


# --------------------------------------------------------------------- CLI
def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=str(COMPONENT))
    parser.add_argument("--check", action="store_true", help="report what breaks a ruling and stop")
    parser.add_argument("--render", action="store_true", help="write the reference fragment to stdout")
    parser.add_argument("--write", default=None, help="write it to this path instead")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    contract = load(root)
    broken = findings(contract)
    for finding in broken:
        print(f"finding: {finding}", file=sys.stderr)
    if broken:
        return 2
    if args.check and not (args.render or args.write):
        print(f"{CONSUMING}: no findings")
        return 0
    text = render(contract)
    if args.write:
        (root / args.write).write_text(text, encoding="utf-8")
        print(args.write)
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
