"""The consuming contract: read `consuming.json`, refuse what breaks it, render a compose file.

**What it does.** Reads this component's `consuming.json` — the machine-readable
half of `docs/consuming.md` — checks it against the rulings a consumer inherits,
and renders a complete, working compose file from it and nothing else.

**How you use it.** From the component root:

    python3 consuming/consuming.py --check           # the rulings, on the real contract
    python3 consuming/consuming.py --render          # the reference fragment, to stdout
    python3 consuming/consuming.py --write docs/compose.reference.yaml
    python3 consuming/consuming.py --run-line        # the runner's documented run line

`load(root)` reads the file; `findings(contract)` returns what is wrong with it,
empty when nothing is; `render(contract, ...)` returns the compose file's text
and **refuses** a contract with a finding rather than emitting one that breaks a
ruling.

⭐ The contract has one block per image this component builds. The EDITOR is
rendered into a compose file here; the RUNNER has no compose file — a reader
starts one container by hand — and its checks and its two documented command
lines live in `consuming/runner.py`, which `findings` calls per block.

**Depends on.** The standard library only. ⛔ It reads no Dockerfile, starts no
container and mounts no socket.

## ⛔ Why a renderer and not a checked-in example

The epic's acceptance is that `consuming.json` is *sufficient to generate a
working compose file with no other input*. A hand-written example cannot show
that: it would be a second copy of the contract, drifting quietly. So the
reference fragment beside `docs/consuming.md` is **generated by this module**
and a test asserts the checked-in file is what the contract renders today.

⭐ Per-project values — the project name, the host port, the uid:gid, the source
paths — arrive as compose **interpolations** with defaults (`${HOST_UID:-1000}`)
or as this module's keyword arguments. So the rendered file needs no argument to
be complete, and a consumer still adapts every part that must differ.

## ⛔ What the rendered file may never say

§8.3 is the non-negotiable: no Docker socket reaches a serving process. The five
rulings E12 gives a consumer are the rest — loopback-only publishing, the sources
and nothing else, the repository owner's uid:gid, a bind source that exists
before the container starts, and a writable root filesystem. `findings` asserts
each of them against the data, so a contract edited into breaking one stops here
instead of in somebody's browser.

## ⭐ What a tag promises, and what `provides` does

Neither image has a registry, so a consumer builds each from a pinned checkout
and pins the tag the build prints. That tag is a **function of the build's
inputs**, which is the whole of its promise: the same inputs compute it,
different inputs compute another one, and no later build can take a pinned name
away. The two images read DIFFERENT inputs — the editor folds the runner's
digest into its own and adds four roots of its own, and the runner knows nothing
about the editor — which is what keeps an editor-only change from moving a
runner tag. The **consuming half** — this file, its document and its renderer —
is versioned by `provides` instead, and moves without moving either tag.
`findings` refuses a tag block that claims otherwise, on either image, and
refuses a `provides` bump with no upgrade note.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path

import runner

COMPONENT = Path(__file__).resolve().parents[1]
CONSUMING = "consuming.json"
#: Where the rendered reference lives, relative to the component root.
REFERENCE = "docs/compose.reference.yaml"
#: The addresses that keep an unencrypted IDE on this machine.
LOOPBACK = ("127.0.0.1", "::1", "localhost")
#: A named part of the tag scheme, which `image.tag.parts` must describe.
_PLACEHOLDER = re.compile(r"\{([a-z_]+)\}")
#: The header every rendered file carries: it is a template, never an include.
HEADER = (
    "# ⛔ A TEMPLATE TO COPY AND ADAPT — never an `include:` and never a file to",
    "# reference from another compose project. The mount list is exactly the part",
    "# that must differ per project, so a shared file would be wrong for everyone.",
    "#",
    f"# ⭐ Generated by `consuming/consuming.py` from `{CONSUMING}`, which is this",
    "# component's contract and the only input. Edit the contract, not this file;",
    "# then copy it into your own repository and adapt it there.",
    "#",
    "# ⛔ No Docker socket is mounted here or anywhere else (spec §8.3).",
)


class Refused(ValueError):
    """A contract that will not be rendered, and which ruling it breaks."""


def load(root: Path = COMPONENT) -> dict:
    return json.loads((Path(root) / CONSUMING).read_text(encoding="utf-8"))


# --------------------------------------------------------------- the rulings
def findings(contract: dict) -> list[str]:
    """What is wrong with the contract, empty when nothing is.

    ⭐ One call per BLOCK, not per ruling (`TC-05/3`): the editor publishes a
    port, mounts named volumes and answers a health check, and the runner does
    none of the three, so `runner.findings` states the rulings they share in
    the runner's own terms rather than threading exceptions through these.

    ⭐ `_tag_findings` is the exception that proves it, and it runs on BOTH
    blocks: nothing about what a tag promises is editor-specific, so the check
    takes a block rather than being copied per image (`TC-06/2`). What differs
    between the two — the repository, the build command, and which input roots
    the digest reads — is data each block states for itself.
    """
    editor = contract.get("editor", {})
    found: list[str] = []
    found += _socket_findings(editor)
    found += _port_findings(editor)
    found += _user_findings(editor)
    found += _mount_findings(editor)
    found += _ordering_findings(editor)
    found += _environment_findings(editor)
    found += _filesystem_findings(editor)
    found += _tag_findings(editor)
    block = contract.get(runner.BLOCK, {})
    found += [f"{runner.BLOCK}: {finding}"
              for finding in runner.findings(block) + _tag_findings(block)]
    found += _release_findings(contract)
    return found


def _socket_findings(editor: dict) -> list[str]:
    """§8.3: never, not behind a flag and not only locally."""
    found = []
    if editor.get("docker_socket") is not False:
        found.append("docker_socket is not declared false: the Docker socket is never mounted (spec §8.3)")
    for mount in editor.get("mounts", []):
        if "docker.sock" in f"{mount.get('host_path', '')}{mount.get('container_path', '')}":
            found.append(f"a mount names the Docker socket: {mount.get('container_path')} (spec §8.3)")
    return found


def _port_findings(editor: dict) -> list[str]:
    """Loopback-only port binding, never 0.0.0.0."""
    found = []
    bound = {port.get("container") for port in editor.get("ports", [])}
    for port in editor.get("ports", []):
        where = port.get("host_bind")
        if where not in LOOPBACK or port.get("publish_on_all_interfaces") is not False:
            found.append(f"port {port.get('container')} is published on {where!r}: an unencrypted IDE "
                         "with a shell binds loopback only")
    for argument in editor.get("command", []):
        if not argument.startswith("--bind-addr"):
            continue
        inside = re.fullmatch(r"--bind-addr=(?P<host>[\w.:\[\]]+):(?P<port>\d+)", argument)
        if not inside or int(inside["port"]) not in bound:
            found.append(f"the command binds {argument!r}, which no ports entry publishes")
    return found


def _user_findings(editor: dict) -> list[str]:
    """Run as the repository owner's uid:gid, or the files it writes are root's."""
    runs_as = editor.get("runs_as", {})
    if runs_as.get("uid") in (None, 0) or runs_as.get("gid") in (None, 0):
        return ["runs_as is root or absent: the container runs as the uid:gid that owns the sources"]
    if not runs_as.get("compose_value"):
        return ["runs_as names no compose value, so a consumer has nothing to put under `user:`"]
    return []


def _mount_findings(editor: dict) -> list[str]:
    """Only the sources are mounted, and a bind source exists before the container starts."""
    workspace = editor.get("workspace", {})
    root = workspace.get("container_path")
    found = []
    if not root or workspace.get("kind") != "tmpfs":
        found.append("the workspace root is not a tmpfs: docker would create it root-owned and no "
                     "build could write into it")
    for mount in editor.get("mounts", []):
        path, kind = mount.get("container_path", ""), mount.get("kind")
        if kind != "bind":
            continue
        if not root or not path.startswith(f"{root}/"):
            found.append(f"the bind at {path} is outside the workspace {root!r}: only the sources are "
                         "mounted, not the repository and not $HOME")
        if mount.get("must_exist_before_start") is not True:
            found.append(f"the bind at {path} does not say its source must exist before the container "
                         "starts; docker creates a missing one root-owned")
    return found


def _ordering_findings(editor: dict) -> list[str]:
    """Ordering is enforced by a health check, not by hope."""
    health = editor.get("healthcheck", {})
    missing = [key for key in ("command", "path", "expect_status", "ordering") if not health.get(key)]
    return [f"the healthcheck declares no {key}: ordering is enforced by a health check, not by hope"
            for key in missing]


def _environment_findings(editor: dict) -> list[str]:
    """A variable with no default is required, and one with a default is not."""
    found = []
    for entry in editor.get("environment", []):
        name, default, required = entry.get("name"), entry.get("default"), entry.get("required")
        if required and default is not None:
            found.append(f"{name} is required and defaulted: a consumer cannot tell which the image expects")
        if required and not entry.get("compose_value"):
            found.append(f"{name} has no default and no compose value, so a consumer has nothing to write")
    return found


def _filesystem_findings(editor: dict) -> list[str]:
    """The image writes outside its mounts, so a read-only root breaks it at start."""
    filesystem = editor.get("filesystem", {})
    found = []
    if filesystem.get("read_only_root") is not False or filesystem.get("compose_value") is not False:
        found.append("filesystem does not declare the root writable: the entrypoint repairs the passwd "
                     "record at every start and the primed caches are written under /opt, so a read-only "
                     "root filesystem breaks the editor at start and every graded run in it")
    protected = filesystem.get("never_read_only") or []
    if not protected:
        found.append("filesystem names no path that must never be mounted read-only")
    for mount in editor.get("mounts", []):
        path = mount.get("container_path", "")
        under = [kept for kept in protected if path == kept or path.startswith(f"{kept}/")]
        if mount.get("read_only") and under:
            found.append(f"the mount at {path} is read-only and {under[0]} must stay writable")
    return found


def _tag_findings(editor: dict) -> list[str]:
    """A tag is computed from its inputs; nothing about it is kept by hand."""
    tag = editor.get("image", {}).get("tag", {})
    if not tag:
        return ["image.tag is absent: a consumer pins a tag with nothing saying what one promises"]
    found = []
    named = set(_PLACEHOLDER.findall(tag.get("scheme", "")))
    described = set(tag.get("parts", {}))
    found += [f"the tag scheme names {{{part}}} and image.tag.parts does not say what it is"
              for part in sorted(named - described)]
    found += [f"image.tag.parts describes {part!r}, which the tag scheme does not name"
              for part in sorted(described - named)]
    if tag.get("is_a_function_of_its_inputs") is not True or tag.get("mutated_in_place") is not False:
        found.append("image.tag does not say the tag is computed from its inputs and never mutated in "
                     "place: a consumer pins a content, not a name a later build may take away")
    if "--print-tag" not in (tag.get("computed_by") or []):
        found.append("image.tag.computed_by is not a command that prints a tag, so nothing computes one")
    for key in ("build_inputs", "moved_by", "not_moved_by", "promises", "does_not_promise"):
        if not tag.get(key):
            found.append(f"image.tag.{key} is empty: what a tag promises is stated, not inferred")
    if not (tag.get("upgrade") or {}).get("re_verify"):
        found.append("image.tag.upgrade names nothing to re-verify, which is not an upgrade note")
    return found


def _release_findings(contract: dict) -> list[str]:
    """Every `provides` a consumer can be holding has an upgrade note, newest first."""
    releases = contract.get("releases") or []
    if not releases:
        return ["releases is empty: a consumer that re-pins has nothing saying what to re-verify"]
    found = []
    numbers = [entry.get("provides") for entry in releases]
    if numbers[0] != contract.get("provides"):
        found.append(f"the newest release is provides {numbers[0]!r} and the contract provides "
                     f"{contract.get('provides')!r}: a bump with no upgrade note is one nobody can act on")
    if numbers != list(range(len(numbers), 0, -1)):
        found.append("releases is not one entry per provides, from 1 and newest first")
    for entry in releases:
        where = entry.get("provides")
        if not entry.get("summary") or not entry.get("re_verify"):
            found.append(f"the release for provides {where!r} says nothing to re-verify")
        if entry.get("moves_every_tag") not in (True, False):
            found.append(f"the release for provides {where!r} does not say whether it moved every tag")
    return found


# ------------------------------------------------------------- the rendering
def render(contract: dict, *, project: str = "studyforge-editor", service: str = "editor") -> str:
    """The compose file this contract describes, or `Refused` naming the ruling it breaks."""
    broken = findings(contract)
    if broken:
        raise Refused("; ".join(broken))
    editor = contract["editor"]
    lines = [*HEADER, "", _scalar("name", project), "", "services:", f"  {service}:"]
    lines += _service(editor)
    volumes = [mount["volume"] for mount in editor["mounts"] if mount["kind"] == "volume"]
    if volumes:
        lines += ["", "volumes:"] + [f"  {name}:" for name in volumes]
    return "\n".join(lines) + "\n"


def _service(editor: dict) -> list[str]:
    at = "    "
    lines = [
        *_comment("The image a consumer PINS. It has no registry: build it from this component's "
                  "checkout and pin the tag the build prints:", at),
        f"{at}#   {' '.join(editor['image']['tag_from'])}",
        *_comment(editor["image"]["tag"]["how_to_pin"], at),
        _scalar("image", editor["image"]["compose_value"], at),
        *_comment(editor["runs_as"]["why"], at),
        _scalar(editor["runs_as"]["compose_key"], editor["runs_as"]["compose_value"], at),
        *_comment(editor["why_restart_no"], at),
        _scalar("restart", editor["restart"], at),
        *_comment(editor["filesystem"]["why"], at),
        _scalar(editor["filesystem"]["compose_key"], editor["filesystem"]["compose_value"], at),
        f"{at}environment:",
    ]
    for entry in editor["environment"]:
        lines += _comment(entry.get("note", ""), f"{at}  ")
        lines.append(_scalar(entry["name"], entry.get("compose_value") or entry["default"], f"{at}  "))
    lines.append(f"{at}ports:")
    for port in editor["ports"]:
        lines += _comment(port["why"], f"{at}  ")
        lines.append(f'{at}  - "{port["host_bind"]}:{port["host"]}:{port["container"]}"')
    lines += [*_comment(editor["workspace"]["why"], at), f"{at}tmpfs:",
              f"{at}  - {editor['workspace']['container_path']}", f"{at}volumes:"]
    for mount in editor["mounts"]:
        lines += _comment(mount["purpose"], f"{at}  ")
        if mount["kind"] == "bind":
            lines += _comment("⛔ This source must exist on the host BEFORE the container starts, or "
                              "docker creates it root-owned and nothing in the container can write it.",
                              f"{at}  ")
        source = mount["host_path"] if mount["kind"] == "bind" else mount["volume"]
        suffix = ":ro" if mount["read_only"] else ""
        lines.append(f'{at}  - "{source}:{mount["container_path"]}{suffix}"')
    lines += [*_comment(editor["command_notes"]["bind_addr"], at),
              *_comment(editor["command_notes"]["workspace_trust"], at), f"{at}command:"]
    lines += [f'{at}  - "{_escaped(argument)}"' for argument in editor["command"]]
    lines += [*_comment(editor["healthcheck"]["ordering"], at), f"{at}healthcheck:"]
    lines += _healthcheck(editor["healthcheck"], f"{at}  ")
    return lines


def _comment(text: str, at: str = "") -> list[str]:
    """A prose value from the contract, wrapped so the rendered file stays readable."""
    if not text.strip():
        return []
    return [f"{at}# {line}" for line in textwrap.wrap(text, width=78 - len(at))]


def _healthcheck(health: dict, at: str) -> list[str]:
    test = ", ".join(f'"{_escaped(part)}"' for part in health["command"])
    lines = [f"{at}test: [{test}]"]
    for key, suffix in (("start_period", "s"), ("start_interval", "s"), ("interval", "s"), ("timeout", "s")):
        lines.append(f"{at}{key}: {health[f'{key}_seconds']}{suffix}")
    return lines + [f"{at}retries: {health['retries']}"]


def _scalar(key: str, value, at: str = "") -> str:
    if isinstance(value, bool):  # YAML's spelling, not Python's
        return f"{at}{key}: {str(value).lower()}"
    if isinstance(value, int):
        return f"{at}{key}: {value}"
    return f'{at}{key}: "{_escaped(str(value))}"'


def _escaped(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


# --------------------------------------------------------------------- CLI
def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=str(COMPONENT))
    parser.add_argument("--check", action="store_true", help="report what breaks a ruling and stop")
    parser.add_argument("--render", action="store_true", help="write the reference fragment to stdout")
    parser.add_argument("--write", default=None, help="write it to this path instead")
    parser.add_argument("--run-line", action="store_true",
                        help="write the runner's documented `docker run` line to stdout")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    contract = load(root)
    broken = findings(contract)
    for finding in broken:
        print(f"finding: {finding}", file=sys.stderr)
    if broken:
        return 2
    if args.run_line:
        print(runner.run_line(contract[runner.BLOCK]))
        return 0
    if args.check and not (args.render or args.write):
        print(f"{CONSUMING}: no findings")
        return 0
    text = render(contract)
    if args.write:
        (root / args.write).write_text(text, encoding="utf-8")
        print(args.write)
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
